# Site settings
title: Kram
email: kram@gustav.tv
description: "A class based programming language"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kramlang.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
