# Site settings
title: Kram
email: kram@gustav.tv
description: "A class-y programming language"
baseurl: ""
url: "http://kramlang.org" # the base hostname & protocol for your site
permalink: /:categories/:title/

highlighter: pygments

syntax-highlighting:
  enabled : true

pretty_categories:
    getting-started: "Getting Started"
    features: "Features"
    std: "Standard Library"
    io: "IO"
    std-list: "List"
    std-map: "Map"